[features]
strict = []
serde = ["dep:serde"]


[package]
name = "quadraturerules"
version = "{{VERSION}}"
edition = "2021"
authors = ["Matthew Scroggs <quadraturerules@mscroggs.co.uk>"]
description = "quadrature rules library"
license = "MIT"
homepage = "https://quadraturerules.org"
repository = "https://github.com/quadraturerules/quadraturerules"
readme = "README.md"
keywords = ["numerics"]
categories = ["mathematics", "science"]

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
approx = "0.5"

[lints.clippy]
wildcard_imports = "forbid"
