name: Make new releases - test

on:
  push:
    branches: ["*"]

jobs:
  julia-library:
    name: Release Julia library
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/checkout@v4

      - run: |
          cd python
          python3 -m pip install .
        name: Install qrtools

      - run: |
          cd library
          python build.py julia
        name: Build Rust library

      - name: Clone Julia source repo
        run: git clone https://github.com/quadraturerules/QuadratureRulesDotOrg.jl QR.jl
      - name: Copy Julia source
        run: cp -r ../library/julia.build/* QR.jl/
      - name: git add and commit
        run: |
          cd QR.jl
          git config --global user.email "julia@mscroggs.co.uk"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -a -m "Update Julia source"
      - name: git push
        run: |
          cd QR.jl
          git remote set-url origin https://x-access-token:${{ secrets.JULIA_REPO_TOKEN }}@github.com/quadraturerules/QuadratureRulesDotOrg.jl
          git push
