name: Test and build

on:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 1"

jobs:
  style-checks:
    name: Run style checks
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/checkout@v3

      - run: |
          python3 -m pip install -r website/requirements.txt
          python3 -m pip install numpy
        name: Install requirements
      - run: python3 -m pip install flake8 mypy pydocstyle isort
        name: Install linting tools
      - run: |
          python3 -m flake8 test
          cd website
          python3 -m flake8 .
        name: Flake8 checks
      - run: |
          python3 -m pydocstyle test
          cd website
          python3 -m pydocstyle .
        name: Pydocstyle checks
      - run: |
          cd website
          python3 -m mypy --install-types --non-interactive .
          python3 -m mypy .
        name: mypy checks
      - run: |
          python3 -m isort --check test
          cd website
          python3 -m isort --check .
        name: isort checks

  build-website:
    name: Build quadraturerules.org
    runs-on: ubuntu-22.04
    if: github.ref != 'refs/heads/main'
    needs:
      - run-tests
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/checkout@v3

      - run: python3 -m pip install -r website/requirements.txt
        name: Install requirements
      - run: |
          cd website
          python3 build.py _html --github-token ${{ secrets.GITHUB_TOKEN }}
        name: Build website HTML
        if: ${{ !github.event.pull_request.head.repo.fork }}
      - run: |
          cd website
          python3 build.py _html
        name: Build website HTML
        if: ${{ github.event.pull_request.head.repo.fork }}

  build-and-push-website:
    name: Build and deploy defelement.com
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/checkout@v3

      - run: python3 -m pip install -r website/requirements.txt
        name: Install requirements
      - run: |
          cd website
          python3 build.py ../_html --github-token ${{ secrets.GITHUB_TOKEN }}
        name: Build website HTML

      # Push to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '_html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  run-tests:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/checkout@v3

      - run: python3 -m pytest test
        name: Run tests with pytest
