name: Test and build quadraturerules.org

on:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 1"

jobs:
  style-checks:
    name: Run style checks
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/checkout@v4

      - run: |
          python3 -m pip install -r website/requirements.txt
          python3 -m pip install -r library/requirements.txt
          python3 -m pip install numpy
        name: Install requirements
      - run: python3 -m pip install flake8 mypy pydocstyle isort
        name: Install linting tools
      - run: |
          python3 -m flake8 test
          python3 -m flake8 library/build.py
          cd website
          python3 -m flake8 .
        name: Flake8 checks
      - run: |
          python3 -m pydocstyle test
          python3 -m pydocstyle library/build.py
          cd website
          python3 -m pydocstyle .
        name: Pydocstyle checks
      - run: |
          cd website
          python3 -m mypy --install-types --non-interactive .
          python3 -m mypy .
        name: mypy checks
      - run: |
          python3 -m isort --check test
          python3 -m isort --check library/build.py
          cd website
          python3 -m isort --check .
        name: isort checks

  build-website:
    name: Build quadraturerules.org
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/checkout@v4

      - run: python3 -m pip install -r website/requirements.txt
        name: Install requirements
      - run: |
          cd website
          python3 build.py _html --github-token ${{ secrets.GITHUB_TOKEN }}
        name: Build website HTML
        if: ${{ !github.event.pull_request.head.repo.fork }}
      - run: |
          cd website
          python3 build.py _html
        name: Build website HTML
        if: ${{ github.event.pull_request.head.repo.fork }}

      - name: Setup Pages
        uses: actions/configure-pages@v3
        if: github.ref == 'refs/heads/main'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_html'
        if: github.ref == 'refs/heads/main'

  push-website:
    name: Build and Deploy quadraturerules.org
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    needs:
      - build-website
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  run-tests:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/checkout@v4
      - run: |
          python3 -m pip install -r website/requirements.txt
          python3 -m pip install -r library/requirements.txt
        name: Install requirements

      - run: |
          python3 -m pip install pytest
          python3 -m pytest test
        name: Run tests with pytest
